spring.application.name=recipeapp

logging.file.name=logs/recipe-app.log

logging.level.root=INFO
logging.level.com.example.recipeapp=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/hambreCeroDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=hambre_user
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true